- libs/common/pix3.zig
Hello there, some small fixes to make samples compile and run when PIX is enabled.
> Makes PIX work with the latest zig version

- libs/win32/d3d11.zig
- libs/win32/dxgi.zig
As defined at here [here](https://docs.microsoft.com/en-us/windows/win32/direct3d11/d3d11-graphics-reference-returnvalues) and [here](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-error) respectively.
I'm using these to turn HRESULTS into zig errors in a project that is only using the win32 lib from this repo. Also, it seems that the COM documentation defines a slightly different set of result codes than the above docs - hence I have left the return codes defined in misc.zig untouched.
On this topic, I'd like to move my error handling code into the win32 library. Would you be open to such changes? (it would be an alternative or potential eplacement to the error handling code in the common lib)
> Define d3d11 and dxgi return codes

- libs/win32/d3d11.zig
- libs/win32/d3dcommon.zig
Enough d3d11 bindings to create a device and swapchain and then get a framebuffer. I'm looking at shader compilation next.
> Add bindings for d3d11 device, swapchain, framebuffer creation

- libs/win32/d3d11.zig
- libs/win32/d3dcommon.zig
- libs/win32/d3dcompiler.zig
- libs/win32/win32.zig
Adds the nessesary bindings to create pixel and vertex shaders on d3d11.
Also adds naughty bindings for d3dcompiler
> d3d11 bindings for vs and ps creation

- libs/zenet/README.md
Minor addition to the sample 'build.zig' in README.md to make it more self-sufficient.
> zenet: Make sample in README.md more self-sufficient

- build.zig
- libs/mach-glfw/system_sdk.zig
- libs/mach-gpu-dawn/build.zig
- libs/zmath/src/zmath.zig
I just installed zig on my M1 MacBook Pro, using homebrew, `brew install zig --HEAD`, and ended up with `zig version 0.10.0-dev.2023+032c722d2`, which reported a few minor compile errors when running `zig build` in the repository root.
- Apparently `std.ChildProcess.init()` no longer returns an error, so the `try` keyword is no longer relevant, but the error message was somewhat confusing to a newb like myself:
```
./build.zig:129:44: error: expected error union type, found 'std.child_process.ChildProcess'
const child = try std.ChildProcess.init(&.{ "git", "submodule", "update", "--init", "--recursive" }, allocator);
^
```
- When the child process is declared `const child`, the next line, `child.cwd = thisDir();` becomes an error:
```
./build.zig:130:24: error: cannot assign to constant …
```
> fix build errors for zig 0.10.0-dev.2023+032c722d2

- libs/zmesh/src/gltf.zig
Hey there, I've started to use `zmesh` in one of the samples I'm working on and found two small issues that prevent my code from compiling. The fixes are simple, but let me know if you'd rather we return `usize` from those two functions.
Cheers!
> zmesh: Fix getNumMeshes and getNumMeshPrimitives

- libs/zd3d12/README.md
- libs/ztracy/README.md
- libs/ztracy/build.zig
- libs/ztracy/src/ztracy.zig
- samples/audio_experiments/build.zig
- samples/audio_playback_test/build.zig
- samples/bindless/build.zig
- samples/bullet_physics_test/build.zig
- samples/directml_convolution_test/build.zig
- samples/intro/build.zig
- samples/mesh_shader_test/build.zig
- samples/minimal/build.zig
- samples/physically_based_rendering/build.zig
- samples/procedural_mesh/build.zig
- samples/rasterization/build.zig
- samples/simple3d/build.zig
- samples/simple_raytracer/build.zig
- samples/textured_quad/build.zig
- samples/triangle/build.zig
- samples/vector_graphics_test/build.zig
Hello Michal - this PR adds support for the Fiber annotations added to Tracy v0.8.0 and above. The actual runtime code is straightforward, but it requires an additional compilation flag (`-DTRACY_FIBERS`) is passed through, so I've added an options struct to the build step. 
According to the Tracy docs this has some small overhead, so I've left it off by default.
With this patch, an async event loop can now mark zones that span suspend points, and Tracy will keep the necessary context to show what the async task (aka fiber / coroutine / green-thread) was doing as though it was a single logical flow of control.
> Added fibers support to ztracy

- libs/zgpu/src/zgpu.zig
This fixes a slight instruction mistake when downloading the Git LFS files after the initial `git clone`.
(Nice work on the libraries by the way, it looks neat)
> zgpu: Fix warning for Git LFS

- libs/zpool/src/embedded_ring_queue.zig
- libs/zpool/src/handle.zig
- libs/zpool/src/main.zig
- libs/zpool/src/pool.zig
Pool() now stores free indices in a queue, and recycles released handles in FIFO order.
Pool.add() now first attempts to issue an unused index within capacity,
then attempts to reuse an index from the free queue,
and failing that will attempt to increase capacity in order to issue a new index.
> zpool v0.2

- libs/zpool/src/embedded_ring_queue.zig
- libs/zpool/src/pool.zig
Added new methods like `getColumnIfLive()`, `getColumnAssumeLive()`, with tests and doc comments.
Renamed `EmbeddedRingQueue.didEnqueue/didDequeue()` to `enqueueIfNotFull()`, `dequeueIfNotEmpty()`.
> Added doc-comments and fail-safe methods to zpool.

- libs/zpool/src/handle.zig
`Handle.cycle` is now stored in the least significant bits of the `Handle.id`, and `Handle.index` is stored in the most significant bits.  Now, when handles are sorted by ascending `Handle.id`, the results will also be in ascending order by `Handle.index`, which could be useful for accessing data indexed by handle in a cache-coherent order.
`AddressableHandle.index` and `AddressableHandle.cycle` are now the same size and type.
> Swap Handle cycle and index positions

- libs/zmath/src/zmath.zig
Those matrices are used frequently in 2D games to have traditional screen coordinates with the origin being at top-level, X and Y coordinates being always positive.
> Add orthographicOffCenter matrix creations functions, 

- libs/zd3d12/src/zd3d12.zig
`GraphicsContext.init` enters an infinite loop if an `ADAPTER_FLAG_SOFTWARE` adapter is found before a suitable one.
> zd3d12: Fix infinite loop on init

- libs/ztracy/src/ztracy.zig
tracy no longer defines '___tracy_init_thread()'.
presumably since '___tracy_set_thread_name()' serves the same purpose
This commit resolves #79
> ztracy: remove InitThread

- libs/zmath/src/zmath.zig
Conditionally skipping math.mod, math.isNearEqual and math.length3 makes 'stage2 build test' pass. 
Tested on zig 0.10.0-dev.3530. Perhaps a useful temporary workaround during the transition from stage1?
> Skip failing math tests on MacOS and stage != 1

- libs/zjolt/libs/JoltC/JoltC.cpp
- libs/zjolt/libs/JoltC/JoltC.h
Adds `GetInverseInteria` through `GetInverseCenterOfMassTransform` in order of API reference
> JoltC: Add more JPH::Body bindings

- libs/zjolt/libs/JoltC/JoltC.cpp
- libs/zjolt/libs/JoltC/JoltC.h
- fixes typos in `JPH_MotionProperties`
- defines `JPH_TransformedShape` and `JPH_SubShapeIDCreator`
- defines remaining JPH_Body_* member fns
> JoltC: Remaining Body bindings

- README.md
- build.zig
- libs/zjobs/README.md
- libs/zjobs/build.zig
- libs/zjobs/src/ring_queue.zig
- libs/zjobs/src/zjobs.zig
This is a candidate for a new zig-gamedev library, `zjobs`.  It provides a generic `JobQueue` implementation that can schedule work to be completed on background threads.  Dependencies between jobs are supported, so you can schedule a job that will not begin until some other job or jobs have completed.  A simple example is provided as a test and in the README, and documentation for each of the public functions in `JobQueue` provides more detailed usage information.
> zjobs v0.1

- libs/zjobs/src/zjobs.zig
Great work from @Avokadoen on the test case for `JobQueue.combine()`.  I chose a different resolution for the compile error they encountered, and restored a loop in `combine()` that allows it to accept more `prereqs` than will fit in a single `CombinePrereqsJob`.  All tests passing on `zig 0.10.0-dev.4280+c3d67c5c4`
> Avokadoen's combine test case with some suggested fixes by Garett

- libs/zstbi/src/zstbi.zig
Allows initializing an image from a buffer and length in memory. The use case for me is reading the contents of an image within a zipped file using a zip library and then creating an image from it to write to a texture and draw with zgui. The only thing I wasn't sure about was HDR images. Should I allow the user to pass that in directly and handle it like the other init function?
> zstbi: Add `stbi_load_from_memory` and `Image.initFromData`

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
Added:
- `ImGui::BeginPopupModal`
- `ImGui::EndPopup`
- `ImGui::OpenPopup`
- `ImGui::CloseCurrentPopup`
- `viewport->Pos`
- `viewport->Size`
Enables:
```zig
if (zgui.button("Open modal")) {
zgui.openPopup("Modal title/id", .{});
}
{
const center = zgui.getMainViewport().getCenter();
zgui.setNextWindowPos(.{
.x = center[0],
.y = center[1],
.cond = .appearing,
.pivot_x = 0.5,
.pivot_y = 0.5,
});
}
if (zgui.beginPopupModal("Modal title/id", .{})) {
if (zgui.button("Close modal", .{})) {
zgui.closeCurrentPopup();
}
zgui.endPopup();
}
```
> zgui: exposed popup modal api

- libs/zgui/src/gui.zig
[Learned that setting `io.IniFilename` to `NULL` will disable `imgui.ini`](https://www.reddit.com/r/imgui/comments/4xstmx/comment/d6jjtlh/?utm_source=reddit&utm_medium=web2x&context=3).
Implemented this by making `zgui.io.setIniFilename` parameter optional.
> allow imgui.ini to be disabled

- libs/zglfw/src/zglfw.zig
Code for getting glfw window attributes.
I use it for checking if window is focused. My main function looks like
```
while (!window.shouldClose()) {
zglfw.pollEvents();
if (!window.getAttribute(zglfw.Window.Attribute.focused)) {
continue;
}
update(&demo);
draw(&demo);
}
```
I'm not sure if this is how you want it implemented, so feel free to rewrite.
I also saw a glfwSetWindowFocusCallback should we have both?
> Get Glfw Window Attributes

- libs/zmesh/src/zmeshoptimizer.zig
_remapVertexBuffer_ incorrectly asserted that destination slice was bigger than source. It will pack vertices in a smaller destination
slice.
> zmesh: remove assert in remapVertexBuffer

- libs/zgui/src/gui.zig
I hit some compile errors trying to use `zgui.beginTable` and this change fixes it.
> fix(zgui): add column arg to BeginTable and fix outer_size paramater type on zguiBeginTable

- libs/zgui/src/gui.zig
Seems like the change that changed the name to `column` didn't change `args.columns` usage in `beingTable` itself
> fix(zgui): use correct name in beginTable, columns -> column

- build.zig
- libs/zd3d12/build.zig
- libs/zd3d12/src/zd3d12.zig
- samples/bindless/build.zig
Hello there 👋 
I was recently working on a project where the 24MB upload heap size was not enough.
I thought it would be a good idea to make it configurable. In this PR I'm proposing the addition of a new build option so that users of the library can choose what best fits their renderer.
Another alternative could be to have this and other values configurable at init time instead, but that seemed like a bigger change.
I'm open to feedback of course
> Make upload_heap_capacity a build option

- libs/zstbi/libs/stbi/stb_image.c
- libs/zstbi/libs/stbi/stb_image_resize.h
- libs/zstbi/src/zstbi.zig
This adds image resizing using the `stbi_image_resize` library to the `zstbi` package. I'm not sure if the `STBIR_MALLOC` and `STBIR_FREE` implementations are correct since I have no idea what `context` is supposed to be so I just delegated to `zstbiMalloc` and `zstbiFree` respectively. It seems to work fine in my application however, with no issues. I'm not sure either if this is the API wanted for something like this, so it's fine if it's not accepted in this state, just opening so something can get in `zstbi` since resizing is a quite common operation in my experience...
> feat(zstbi): add image resizing

- libs/zstbi/libs/stbi/stb_image.c
- libs/zstbi/libs/stbi/stb_image_write.h
- libs/zstbi/src/zstbi.zig
Implements writing `zstbi.Image`s as PNG or JPEG to a file using `stb_image_write`. I did not add the other formats `stb_image_write` supports because I do not need those.
> feat(zstbi): implement writing images as jpeg or png files

- libs/zwin32/src/d3d12.zig
Hello there, this PR simply adds the missing GUID for ID3D12QueryHeap.
I've tested this code on a project I'm working on and it works fine, but let me know if I should add a test or something :)
> Add missing IID_IQueryHeap

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
- Added AddInputCharactersUTF8 
- Fix typo in Key enum 
- Convert key modifiers from u32 to Key. This is because the modifiers can't really be registered with addKeyEvent otherwise since zig's type safety does not allow you to cast these values to enum as they are outside enum range.
> zgui: minor fixes and AddInputCharactersUTF8

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/src/dxgi.zig
Hello there, this PR adds support for IDXGIAdapter3. I need this to query info about the memory usage of my apps via `IDXGIAdapter3.QueryVideoMemoryInfo`.
I've tested that everything builds correctly and I've run the `bindless` sample with Debug Layers on and everything works correctly without any additional warnings or errors.
I've also exposed the `adapter` via the `GraphicsContext` and I release it when the `GraphicsContext` gets deinitialized. I'm not sure if there's another way to get the `adapter` from the `device`. If there's a way I'm okay with removing the `adapter` from `GraphicsContext`.
Cheers!
> d3d12: Add support for IDXGIAdapter3

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/src/wincodec.zig
Hello again, I've encountered some 64bbp RGBA textures on [Poly Haven](https://polyhaven.com/) and had to add support for them to wincoded.zig and zd3d12.zig.
I also have a question a bit related to this. Have you planned or thought about adding support for loading DDS textures? I used them in my C++ experiments via [DirectXTK12](https://github.com/Microsoft/DirectXTK12) and they're really nice to work with. It might also be something I can help with if you want.
Cheers
> Add support for loading 64bpp RGBA textures

- libs/zmath/src/zmath.zig
- Both `orthographicOffCenter()` functions were mistakenly defined as column-major and didn't work, so I transposed them to row-major.
- Added OpenGL variants of all orthographic functions that work with Z [-1, 1].
I've tested and verified all 8 orthographic functions locally and they seem to behave as expected. Let me know if you want me to provide anything.
> zmath: Fix orthographic functions; add Z [-1, 1] variants

- libs/zwin32/src/zwin32.zig
This small change allows me to avoid the following error when cross-compiling with zwin32 package present
```
/home/chris/zig/0.11.0-dev.1390+74b72a766/files/lib/std/os.zig:151:24: error: root struct of file 'c' has no member named 'fd_t'
pub const fd_t = system.fd_t;
~~~~~~^~~~~
referenced by:
Handle: /home/chris/zig/0.11.0-dev.1390+74b72a766/files/lib/std/fs/file.zig:31:26
File: /home/chris/zig/0.11.0-dev.1390+74b72a766/files/lib/std/fs/file.zig:15:13
File: /home/chris/zig/0.11.0-dev.1390+74b72a766/files/lib/std/fs/file.zig:13:18
File: /home/chris/zig/0.11.0-dev.1390+74b72a766/files/lib/std/fs.zig:15:40
File: /home/chris/zig/0.11.0-dev.1390+74b72a766/files/lib/std/io.zig:12:20
getStdErr: /home/chris/zig/0.11.0-dev.1390+74b72a766/files/lib/std/io.zig:74:20
print__anon_11782: …
```
> zwin32.zig use std.log.debug instead of std.debug.print

- libs/zbullet/libs/cbullet/cbullet.cpp
- libs/zbullet/libs/cbullet/cbullet.h
- libs/zbullet/src/zbullet.zig
Needed these to disable collision for "sensor-like" objects. Lots of other neat things you can do with them apparently, like disabling debug drawing for a body.
> zbullet: Add Body.setCollisionFlags

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
This is useful for adding context menus to tree nodes items and similar.
> zgui: Expose `beginPopupContextItem`

- libs/zmesh/build.zig
- libs/zmesh/libs/meshoptimizer/indexgenerator.cpp
- libs/zmesh/libs/meshoptimizer/meshoptimizer.h
- libs/zmesh/libs/meshoptimizer/simplifier.cpp
- libs/zmesh/src/zmeshoptimizer.zig
- samples/bindless/src/bindless.zig
Hello there, this PR upgrades `meshoptimizer` to version 0.18 and exposes `meshopt_simplify` and `meshopt_simplifySloppy`.
I've tested both `simplify` and `simplifySloppy`, but the SciFi Helmet couldn't be simplified via `simplify`. I was able to produce some LODs via `simplifySloppy` instead.
I'm not sure if the `bindless` sample is the best place for also showing how to LOD, but for now I've put them there.
> zmesh simplify

- libs/zpool/src/handle.zig
I found myself wanting to return handles from exported functions for FFI use. I think it makes sense to make handles `extern` to make this easier, since handles are just a wrapped integer anyways.
(There shouldn't be any performance penalty doing this, right?)
> zpool: Make handles extern for better C interop

- libs/zgui/README.md
- libs/zgui/build.zig
- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
- Add build option to generated a shared library
- Add gui.initNoContext / gui.deinitNoContext
- Update ConfigFlags to be a packed struct
- Add gui.menuItemPtr / zguiMenuItemPtr
- Add extern "C" and ZGUI_API define to zgui.cpp
> Support building dependencies as a shared library

- libs/zopengl/src/zopengl.zig
This allows for loaders that return extern zig fn ptrs (ie are const)
> [zopengl] const procs ptrs

- libs/zopengl/build.zig
- libs/zopengl/src/bindings.zig
- libs/zopengl/src/wrapper.zig
- libs/zopengl/src/zopengl.zig
It's nice to have some extra type safety when working with OpenGL to avoid easy mistakes that would otherwise require some kind of runtime checks or debugging to find.
This is a tentative attempt at implementing a very minimal, thin wrapper around the bindings to add some safety and convenience. I am trying to achieve zero or near-zero overhead in release modes and not restrict use of the API in any way.
I've covered a subset of the API here to use as a point of discussion (some require more attention than others):
`texParameteri`, `texImage2D`, `clear`, `clearColor`, `getError`, `drawArrays`, `bindTexture`, `genTextures`, `bindBuffer`, `genBuffers`, `bufferData`, `bufferSubData`, `attachShader`, `compileShader`, `createProgram`, `createShader`, `deleteShader`, `enableVertexAttribArray`, …
> zopengl: optional thin "zigified" wrapper (experimental)

- libs/zglfw/src/zglfw.zig
Just a tiny change to add a `glfwSetTime` wrapper to zglfw.
It's a good practice when using `glfwGetTime` to occasionally also use `glfwSetTime` to reset the counter (and do whatever else you need to ensure the discontinuity doesn't manifest itself in your simulation logic).  Otherwise you eventually start losing floating point precision and that can cause a lot of subtle issues.
> Expose glfwSetTime in zglfw

- libs/zglfw/src/zglfw.zig
This exposes the GLFW APIs for:
- Setting window size (getter already exists)
- Getting and setting window position
- Changing window title after creation
- Setting additional window callbacks:
- Size
- Framebuffer Size
- Position
- Content scale (for when windows move between monitors with different DPI)
Generally most games don't need these since they run in fullscreen, but for tooling and non-game uses, they're a necessity IMHO.
> Expose GLFW functions for windowed mode apps

- libs/zmath/src/zmath.zig
Hi, a couple of nice lerp-like functions :) I think they are correct but I've only used map_linear for now. I believe they conform to the style of zmath, let me know if you want me to change anything.
> zmath: Added lerp_inverse and map_linear.

- libs/zpool/src/pool.zig
Noticed this constructor is not used anywhere, so it was silently broken. Would probably make sense to test adding/removing handles from a 0 capacity pool as well, but for now I just added a simple test so the init() function is compiled and analyzed by Zig.
> zpool: Fix broken Pool.init()

- libs/ztracy/build.zig
Fixes ztracy build for macOS. Without this, compiling Tracy cpp client fails with `fatal error: 'mach/mach_vm.h' file not found`
> ztracy: add macos frameworks search path

- libs/zopengl/src/zopengl.zig
I'm not sure how I let this one creep in but it doesn't exist in ES profile, sorry!
Seems like some desktop drivers will load something even if in ES mode. I will verify with different driver from now on
> zopengl: glFramebufferTexture does not exist in ES profile

- libs/zopengl/src/wrapper.zig
- rename TextureInternalFormat to InternalFormat
- add missing InternalFormats
- define Renderbuffer distinct type
- defer RenderbufferTarget enum
- define FramebufferTarget, FramebufferAttachment and FramebufferAttachmentParameter enums
- wrap some framebuffer and renderbuffer APIs
> zopengl: wrapper progress

- libs/zopengl/src/wrapper.zig
The wrapper maps gl enums to distinct types for convenience of the programmer. However, considering a potential situation where a particular opengl driver returns a non-spec-conforming value we should be careful to not assume a valid value. But note in many cases, the application may continue on without issues.
For a very small performance cost, by taking more care when mapping gl ints/enums to Zig enums, this change will prevent checkFramebufferStatus from crashing in such a situation (release mode) and also provide more information to the programmer in non-release mode.
Also cleaned up getError implementation, which is a similar case.
> zopengl: wrapper runtime safety

- build.zig
Expose for usage in project tracking same Zig version as zig-gamedev dependency
> build.zig: expose min_zig_version

- libs/zopengl/src/bindings.zig
- libs/zopengl/src/wrapper.zig
- libs/zopengl/src/zopengl.zig
Bindings:
- Define core 4.3 debug api & KHR_debug
- Separate ES extension enum from "desktop" extension enum
- Introduce bind util fn for binding gl procs to multiple symbols. This is useful for binding ES flavoured proc names to their "desktop" equivalent for convenience of programmer writing cross-platform gl
Wrapper:
- Define `DebugSource`, `DebugType` and `DebugSeverity` enums
- Wrap `debugMessageCallback`
- Remove superfluous ES flavour from wrapper; wrapper uses aliased bindings where appropriate
- Add `vertex_array_binding` to `ParameterName` enum
> zopengl: debug api bindings & ES aliasing

- libs/zaudio/README.md
Beforehand neither `engine.destroy()` or `music.destroy()` was called, this fixes that, so now this sample code runs and exits cleanly
> Fix memory leak in zaudio sample code

- libs/zpool/src/pool.zig
I noticed that `requireLiveHandle` (as well as `getColumns` and probably more) could return `error.PoolIsFull`. I switched from the explicit `Error!...` to an implicit error set to fix this.
I also see that the possible errors are listed in the documentation, but maybe it would be better to remove those and use an explicit error set (one that doesn't include `error.PoolIsFull`). Then `Error` could be defined as, for example, `error{PoolIsFull} || HandleError`. Let me know if you'd prefer that solution and I can update this PR :)
> zpool: Fix incorrect error set in requireLiveHandle

- libs/zflecs/README.md
The README in `zflecs` seems to have an artifact from the previous `zsdl` README; this PR corrects that to the proper library.
> zflecs: correct typo in readme

- libs/zjobs/src/zjobs.zig
This fix makes  `test "JobQueue throughput"`  use less jobs in such systems.
> [zjobs] Make throughput test work on systems with 2-4 GiB of RAM

- libs/zglfw/src/zglfw.zig
i was unsure where to put the clipboard functions as they take a ``window`` parameter but glfw docs say that its deprecated and can also just take null. not familiar with the standard way of handling strings with extern C functions so ill gladly change something if needed.
> zglfw: add setClipboardString, getClipboardString, and setDropCallback

- libs/zflecs/src/zflecs.zig
When I first started integrating zflecs I had a difficult time tracking down some assertions. 
At the moment flecs internal assertions kill your application without hitting a breakpoint and don't give you any more info than what you see below.
```
D:\Projects\zig-gamedev\libs\zflecs>zig build test
run zflecs-tests: error: fatal: flecs.c: 8845: assert: entity != 0 INVALID_PARAMETER
run zflecs-tests: error: while executing test 'test.zflecs.do_something_wonky', the following command exited with code 3 (expected exited with code 0):
D:\Projects\zig-gamedev\libs\zflecs\zig-cache\o\6e293e5c127177595bffab996fe9a99a\zflecs-tests.exe --listen=-
Build Summary: 2/4 steps succeeded; 1 failed; 5/5 tests passed (disable with -fno-summary)
test transitive failure
+- run zflecs-tests failure
+- zig test …
```
> zflecs: dump stacktrace when flecs calls abort

- libs/zsdl/src/zsdl.zig
* Remove unused SDL3 def
* Rename `Rectangle` to cononical SDL name `Rect`
* Define `Surface` and `Surface.free`
* Move `SDL_RenderCreateTexture` from `Texture` struct to `Renderer` struct
* Add `Texture.query` and `SDL_TextureQuery` binding
* Add `Renderer.createTextureFromSurface` and `SDL_CreateTextureFromSurface` binding
* Fix `Renderer.copy{x}`/`SDL_RendererCopy{x}` src and dst arg types to be optional/nullable
Requesting @Jack-Ji's review of these changes
> zsdl: fixes, tweaks, additions

- libs/zgpu/src/zgpu.zig
- samples/audio_experiments/src/audio_experiments.zig
- samples/audio_experiments_wgpu/src/audio_experiments_wgpu.zig
- samples/bindless/src/bindless.zig
- samples/bullet_physics_test_wgpu/src/bullet_physics_test_wgpu.zig
- samples/directml_convolution_test/src/directml_convolution_test.zig
- samples/gamepad_wgpu/src/gamepad_wgpu.zig
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
- samples/instanced_pills_wgpu/src/instanced_pills_wgpu.zig
- samples/layers_wgpu/src/graphics.zig
- samples/mesh_shader_test/src/mesh_shader_test.zig
- samples/physically_based_rendering_wgpu/src/physically_based_rendering_wgpu.zig
- samples/physics_test_wgpu/src/physics_test_wgpu.zig
- samples/procedural_mesh_wgpu/src/procedural_mesh_wgpu.zig
- samples/rasterization/src/rasterization.zig
- samples/simple_raytracer/src/simple_raytracer.zig
- samples/textured_quad_wgpu/src/textured_quad_wgpu.zig
- samples/triangle_wgpu/src/triangle_wgpu.zig
I tried to compile zig-gamedev with the latest Zig version (`0.11.0-dev.3677+e95fc2023`) and got a lot of deprecation messages about `std.math.min` and `std.math.max`, which are now `@min` and `@max`. I saw this was a reported issue (#318) that got resolved by PR #319, but it looks like some were missed. This PR should hopefully resolve all of the deprecation messages.
> Fully fix issue 318: std.math.max, std.math.min deprecated

- build.zig
Fix breaking zig change, see #320.
> Fix #320: Replace std.builtin.Version in favor of std.SemanticVersion

- libs/zpool/src/pool.zig
- samples/audio_experiments_wgpu/src/audio_experiments_wgpu.zig
I found that `audio_experiments_wgpu` sample would crash after a few mins with an integer overflow:
- The iterators inside pool could overflow their loop counters when pool is full.
- The sample app itself was filling a pool due to not properly releasing handles.
> zpool: Fix int overflows

- libs/zglfw/src/zglfw.zig
The GLFW backend for ImGui sets input callbacks which get discarded when subsequent calls are made to `window.set*Callback` functions. Adding the return values to these functions allows the caller to handle cases where the callbacks have already been set, without the need to reimplement the ImGui backend input handling.
> Add return values to GLFW set callback functions

- libs/zgui/src/plot.zig
- libs/zgui/src/zgui.cpp
Adds the `plotText` call, useful for putting text onto charts next to points.  One thing I haven't figured it out is how to link the plots to a plot so that toggling the plot in the legend also toggles the text...
> add `plotText` to zgui.plot

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
Let me know if this isn't the way you'd put this part of the API together. I can redo this any way you'd like.
I just threw something in there quickly because I needed it, and I've tested it by using it in my own project.
I haven't written these into the actual tests yet though.
I combined each of Jolt's three existing inheritors of the DecoratedShape base class into the same type in the Zig API, because including the complexity of that two-deep inheritance seemed unnecessary. Again, let me know if you disagree.
> zphysics: Added Decorated Shapes

- libs/zsdl/build.zig
- libs/zsdl/src/zsdl.zig
I know this doesn't look very valuable. This is part of a series of small changes to move us a little closer to a future SDL3 migration. The general intention is to minimize potential for conflicts and to make sdl2/sdl3 diffs more pleasant to read as they are developed in parallel.
> zsdl: compile error if use ttf but not enabled

- libs/zphysics/src/zphysics.zig
Seems to be a test issue. Check this again after 0.11 is released.
> Skip failing zphysics test on aarch64_macos

- libs/zsdl/src/sdl2.zig
- Use "distinct" ID types
- In future, we  may want to make these properly distinct if the distinct typedefs proposal is accepted (https://github.com/ziglang/zig/issues/1595)
- Make `EventType` non-exhaustive
- Allows for user-defined event types
- Tidying up, move `MouseWheelDirection` to mouse section
> zsdl tweaks

- libs/zgui/build.zig
- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
For example, if I want to use other backends, it's better to link in imgui myself
> Add option to zgui to use imgui out of source

- libs/zmath/src/zmath.zig
This commit has breaking changes: https://github.com/ziglang/zig/commit/387b0ac4f1c54cb2f83792299aa628a316e17d88
> Fix breaking zig change: deprecated float NaN constants

- build.zig
- libs/zgui/README.md
- samples/minimal_zgpu_zgui/README.md
- samples/minimal_zgpu_zgui/build.zig
- samples/minimal_zgpu_zgui/minimal_zgpu_zgui_content/Roboto-Medium.ttf
- samples/minimal_zgpu_zgui/screenshot.png
- samples/minimal_zgpu_zgui/src/minimal_zgpu_zgui.zig
I am deliberately letting the program crash at the moment, rather than using the commented out line in this sample's build.zig, since the commented out line wasn't necessary in the other samples. In other samples `exe_options.addOption([]const u8, "content_dir", content_dir);` "just works".
If someone could verify that the program also crashes for them, that'd be great. A tip on why the crash occurs/how to fix the crash would be even better, of course! :)
Any stylistic feedback that doesn't add more than one or two lines of code is also welcome.
> Add sample minimal_zgpu_zgui

- libs/zwin32/src/w32.zig
- Add [GetWindowLongPtrA](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlongptra) and [SetWindowLongPtrA](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptra).
- Add a few more [WM_* window message](https://learn.microsoft.com/en-us/windows/win32/winmsg/window-notifications) definitions.
> w32 additions

- libs/zmath/README.md
a8db2f6e0bc2482b2522a5b7405b60d65f2b5e77 inadvertently removed `const` which causes
> error: use of undeclared identifier 'zmath_pkg'`
> &nbsp;&nbsp;&nbsp;&nbsp;zmath_pkg = zmath.package(b, target, optimize, .{
> &nbsp;&nbsp;&nbsp;&nbsp;^~~~~~~~~
> zmath: fix getting started in README.md

- libs/zmath/src/zmath.zig
See https://github.com/ziglang/zig/commit/6a29646a553a93fc6a4cbf0fee5fa5362483c326
After this commit, 4 zmath tests will fail.
> Fix zig breaking change: Rename 'fabs' to 'abs'

- libs/zmath/src/zmath.zig
Enable 3 skipped tests that now work on macOS.
There are still 4 skipped tests, they fail after calling 'math.inf'.
> Enable skipped zmath tests

- libs/zsdl/src/sdl2.zig
- libs/zsdl/src/sdl3.zig
The vulkan methods implemented for sdl3 may also work for sdl2, but I didn't test that, so I didn't PR it.
The struct that serves as a bitfield that mimics SDL's window flags enum was 3 bits off for the vulkan and metal flags. After moving those flags 3 bits further toward the big end, my vulkan tests worked, and the math works out.
I suspect nobody had actually tried creating a vulkan or metal surface with zsdl yet, which is why this hadn't yet been fixed.
> zsdl: Vulkan support for SDL3, corrected window flag bitfield struct for both SDL3 and SDL2

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
Which is useful for getting the translation from Jolt's calculated center of mass frame back to the frame you used when creating the shape, if those are different. In the case of convex hulls, for example, they're often different.
> zphysics: Implemented Shape.getCenterOfMass

- libs/zopengl/build.zig
- libs/zopengl/build.zig.zon
Allows zopengl to be consumed by Zig pkg manager
> make zopengl pkg manager compatible

- README.md
- libs/zglfw/build.zig
- libs/zglfw/build.zig.zon
<details>
<summary>build.zig.zon</summary>
```zig
.{
.name = "example",
.version = "0.1.0",
.paths = .{""},
.dependencies = .{
.zglfw = .{
.path = "./libs/zglfw",  
},
},
}
```
</details>
<details>
<summary>build.zig</summary>
```zig
pub fn build(b: *std.Build) !void {
...
const zglfw = b.dependency("zglfw", .{
.target = target,
.optimize = optimize,
});
const exe = b.addExecutable(.{
.name = name,
.root_source_file = .{ .path = "src/example.zig" },
.target = target,
.optimize = optimize,
});
exe.linkLibrary(zglfw.artifact("libglfw"));
exe.addModule("zglfw", zglfw.module("zglfw"));
...
```
</details>
zglfw can then be imported and used as usual
system-sdk is still currently required to be colocated with zglfw. Hence, this only allows zglfw to be consumed as a dependency by path and not by …
> make zglfw consumable by package manager

- libs/zmath/build.zig
- libs/zmath/build.zig.zon
This aims to be a first step / PoC in enabling use of the libs in this repo as individual dependencies.
This justs exposes the zmath package so that it can added as a dependency in a `build.zig` file with:
```zig
b.dependency("zmath", .{}); // .{ .enable_cross_platform_determinism = false } or .{} which defaults to .enable_cross_platform_determinism = true
exe.addModule("zmath", zmath.module("zmath"));
```
If this is deemed fine, this can be applied to others libs later on.
No other build file has been touched (namely samples), guess it would be better to do it in one fell swoop once all libs are available as dependencies.
> Enable having zmath as a dependency

- libs/zd3d12/src/zd3d12.zig
This PR allows apps that use zd3d12 to resize their window.
I also introduced a new struct for `SwapchainBuffer`s because before we were assuming that swapchain buffers were always allocated at the beginning of the `rtv_heap`. But that's no longer the case, so now we also store the `CPU_DESCRIPTOR_HANDLE` along side the `ResourceHandle`.
> zd3d12: Allow window resizing

- libs/zgui/build.zig
Fixes #453
Enable linker_allow_shlib_undefined if zgui is built as a shared library on macos. This resolves the `undefined reference to symbol` errors you would get before.
> Fix building zgui as a shared lib on macOS

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
This PR fixes a few minor spellings in `JoltPhysicsC.H`
> Correct minor typos in `JoltPhysicsC.h`

- libs/zgui/README.md
Add a missing step to the readme: describe how to copy and adjust the `build.zig.zon` file.
Closes #445
> Improve zgui README

- README.md
- build.zig
Bumps latest verified version to 0.12.0-dev.1871+e426ae43a which becomes our first "pinned" version.
> Introducing new Zig version tracking model

- libs/zgui/src/gui.zig
Making DrawList buffer data non-const and adding helpers for obtaining slices into the buffer data.
Fixes #372
> zgui: Expose slices into DrawList data

- libs/zphysics/src/zphysics.zig
Currently passes on both main and unstable.
> zphysics: enable skipped test

- libs/zmath/src/zmath.zig
These tests fail on Apple Silicon but pass on Intel.
> zmath: skip failing Mac tests only on Apple Silicon

- libs/zgpu/src/zgpu.zig
Adds a field to `GraphicsContextOptions` to allow specifying the wgpu required features when creating a graphical context.
Fixes #465
> [zgpu] wgpu required features option

- libs/zopengl/src/wrapper.zig
It appears to me that the fields in the clear function Bitfield are slightly out of order so this PR attempts to fix that.
If I have missed something, or more is needed for this PR, please let know as I will be happy to correct anything.
As reference:
pub const DEPTH_BUFFER_BIT = 0x00000100;
pub const STENCIL_BUFFER_BIT = 0x00000400;
pub const COLOR_BUFFER_BIT = 0x00004000;
Thanks!
> zopengl: fixed the order of the fields in the wrapper clear Bitfield

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
This PR adds the ImGui Drag And Drop API, which was missing, to zgui.
I tested some basic functionality (essentially reimplemented the example in `imgui_demo.cpp` [here](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L2353)) and it seems to work.
I'm not sure whether the C++ code is formatted correctly, I did it by hand but I don't know if I'm supposed to run it through some formatter.
> zgui: Add Drag And Drop API

- libs/zglfw/src/zglfw.zig
Very single PR - just added binding to the `glfwSetCharCallback` function from glfw. This function sends codepoints to the callback function when a key is pressed. e.g. when you press the compose key and they `<` and `<` again, you'd get the codepoint 0x00AB sent to the callback `«`.
This should resolve [Issue 487](https://github.com/zig-gamedev/zig-gamedev/issues/487)
> Added binding to glfwSetCharCallback

- libs/zglfw/src/zglfw.zig
- libs/zopengl/src/bindings.zig
- libs/zopengl/src/wrapper.zig
Added `debug_output` into `Capability`, and associated constants. Resolves [Issue 489](https://github.com/zig-gamedev/zig-gamedev/issues/489)
> [zopengl] added debug_output into Capability

- build.zig
- samples/frame_pacing_wgpu/README.md
- samples/frame_pacing_wgpu/build.zig
- samples/frame_pacing_wgpu/frame_pacing_wgpu_content/Roboto-Medium.ttf
- samples/frame_pacing_wgpu/screenshot.png
- samples/frame_pacing_wgpu/src/frame_pacing_wgpu.zig
Added a new frame pacing sample which would be required as part of #251 for fullscreen vsync off frame limited rendering to minimize input lag.
> added frame pacing sample

- libs/zstbi/src/zstbi.zig
Hi folks!
I am working on integrating stb_image into Zig for a small project and I found this repo to be an awesome source of inspiration! Great job!
This small PR adds some tests to stb_image libraries.
The last test, where I'm trying to save a JPEG image, is failing with this long error:
```
zig version
0.12.0-dev.2631+3069669bc
zig test src/zstbi.zig -cflags -std=c99 -- /root/PWD/libs/stbi/stb_image.c -lc --cache-dir /root/PWD/zig-cache --global-cache-dir /root/.cache/zig -I /root/PWD/vendor
Test [3/3] test.zstbi write... Illegal instruction at address 0x10c306c
libs/stbi/stb_image_write.h:1263:14: 0x10c306c in stbiw__jpg_writeBits (/root/PWD/libs/stbi/stb_image.c)
bitBuf <<= 8;
^
libs/stbi/stb_image_write.h:1363:7: 0x10c2717 in stbiw__jpg_processDU (/root/PWD/libs/stbi/stb_image.c) …
```
> zstbi tests

- libs/ztracy/src/ztracy.zig
Added TracyAllocator to ztracy.
In the not-used case, the allocator just returns the child_allocator, a true zero-cost abstraction.
In the used case, it returns a new allocator that wraps the child_allocators alloc, resize, and free functions, recording the Alloc, Free/Alloc, or Free with tracy if they succeed or recording a message if not.
> Added TracyAllocator to ztracy

- libs/zopengl/src/bindings.zig
- libs/zopengl/src/zopengl.zig
shaderStorageBlockBinding 
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glShaderStorageBlockBinding.xhtml
getProgramResourceIndex
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetProgramResourceIndex.xhtml
> Add shaderStorageBlockBinding support for std430 buffers

- libs/zflecs/src/zflecs.zig
Need `ecs_set_threads`. Tought I might as well add everything after `ecs_progress` and down from the header
> zflecs: Add a few more functions to the bindings

- README.md
- build.zig
- libs/zglfw/src/zglfw.zig
- libs/zgpu/README.md
- libs/zgpu/build.zig
- libs/zgpu/build.zig.zon
- libs/zgpu/src/zgpu.zig
- samples/audio_experiments_wgpu/src/audio_experiments_wgpu.zig
- samples/bullet_physics_test_wgpu/src/bullet_physics_test_wgpu.zig
- samples/frame_pacing_wgpu/src/frame_pacing_wgpu.zig
- samples/gamepad_wgpu/src/gamepad_wgpu.zig
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
- samples/instanced_pills_wgpu/src/instanced_pills_wgpu.zig
- samples/layers_wgpu/src/graphics.zig
- samples/minimal_glfw_d3d12/src/minimal_glfw_d3d12.zig
- samples/minimal_zgpu_zgui/src/minimal_zgpu_zgui.zig
- samples/monolith/src/monolith.zig
- samples/physically_based_rendering_wgpu/src/physically_based_rendering_wgpu.zig
- samples/physics_test_wgpu/src/physics_test_wgpu.zig
- samples/procedural_mesh_wgpu/src/procedural_mesh_wgpu.zig
- samples/textured_quad_wgpu/src/textured_quad_wgpu.zig
- samples/triangle_wgpu/src/triangle_wgpu.zig
Removes zglfw dependency from zgpu. Introduces `WindowProvider` struct which the user fills out when creating a `GraphicsContext`
For example, to setup a `GraphicsContext` using zglfw:
```zig
const gctx = try zgpu.GraphicsContext.create(
alloctor,
.{
.window = window,
.fn_getTime = @ptrCast(&zglfw.getTime),
.fn_getFramebufferSize = @ptrCast(&zglfw.Window.getFramebufferSize),
.fn_getWin32Window = @ptrCast(&zglfw.getWin32Window),
.fn_getX11Display = @ptrCast(&zglfw.getX11Display),
.fn_getX11Window = @ptrCast(&zglfw.getX11Window),
.fn_getCocoaWindow = @ptrCast(&zglfw.getCocoaWindow),
},
.{}, // default context creation options
);
```
Platform specific fn pointers default to `undefined`
> [zgpu] Remove zglfw dependency

- libs/zflecs/src/zflecs.zig
As of <https://github.com/ziglang/zig/pull/19190> `PerTypeGlobalVar` no longer generates a unique global variable for each `in_type`. The fix is to capture `in_type` in the returned struct.
This should be backwards compatible with the version of zig `zig-gamedev` targets.
> zflecs: Fix PerTypeGlobalVar for latest zig

- build.zig
- libs/zgui/build.zig
- libs/zgui/src/backend_glfw_dx12.zig
- libs/zgui/src/gui.zig
- samples/minimal_zgui_glfw_d3d12/README.md
- samples/minimal_zgui_glfw_d3d12/build.zig
- samples/minimal_zgui_glfw_d3d12/minimal_zgui_glfw_d3d12_content/Roboto-Medium.ttf
- samples/minimal_zgui_glfw_d3d12/src/minimal_zgui_glfw_d3d12.zig
Looking for feedback on how to improve this call:
https://github.com/zig-gamedev/zig-gamedev/pull/519/files#diff-5d56ea36cb7e424a98b9756f43f8ed65fac2bbe159384ccecc0df12dc3c5d985R63
I didn't want to add [`zwin32.d3d12.CPU_DESCRIPTOR_HANDLE`](https://github.com/zig-gamedev/zig-gamedev/blob/193a1d278f2b4970745c171056c6480bca64bbf5/libs/zwin32/src/d3d12.zig#L64-L66) as a dep in zgui, so I ended up using a `@bitCast`.
Ditto for [`zwin32.dxgi.FORMAT`](https://github.com/zig-gamedev/zig-gamedev/blob/193a1d278f2b4970745c171056c6480bca64bbf5/libs/zwin32/src/dxgi.zig#L23).
The alternative is just to add some build conditions to only pull in zwin32 when using glfw_dx12 backend
> added zgui glfw+dx12 backend and sample

- libs/zflecs/src/zflecs.zig
Doing cleanup of `component_ids_hm` before calling `ecs_fini` messes up calls to `ecs.id` during cleanup. For example, you cannot safely use `ecs.id` in an observer that runs `OnRemove` as those can trigger on teardown.
> zflecs: Move `ecs_fini` up in the `fini` wrapper

- libs/zgui/src/gui.zig
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
This PR fixes the following misalignments:
1. The definition of [`ImGuiColorEditFlags_`](https://github.com/zig-gamedev/zig-gamedev/blob/a199efd5de1e861b60c92a7e98ac2fcb8f66bfde/libs/zgui/libs/imgui/imgui.h#L1633) skips the 0th flag.
2. Removed 2 [`ImGuiTabBarFlags_`](https://github.com/zig-gamedev/zig-gamedev/blob/a199efd5de1e861b60c92a7e98ac2fcb8f66bfde/libs/zgui/libs/imgui/imgui.h#L1105-L1106) internal consts
3. Added 3 missing [`ImGuiHoveredFlags_`](https://github.com/zig-gamedev/zig-gamedev/blob/a199efd5de1e861b60c92a7e98ac2fcb8f66bfde/libs/zgui/libs/imgui/imgui.h#L1289-L1291) fields
4. Removed 2 [`ImGuiPopupFlags_`](https://github.com/zig-gamedev/zig-gamedev/blob/a199efd5de1e861b60c92a7e98ac2fcb8f66bfde/libs/zgui/libs/imgui/imgui.h#L1059-L1060) internal consts
5. Fixed …
> audited and fixed zgui flags

- libs/zflecs/README.md
- libs/zflecs/build.zig
I couldn't get this build to work in blockens without these changes I think it needed an install artifacts and a different name than the package?
I modeled this after the imgui build.zig
My zig version: 0.12.0-dev.3428+d8bb139da
I also made this change for main because I think this is a problem in main too maybe?
> Fix zflecs build.zig, no artifact for flecs

- libs/zphysics/src/zphysics.zig
> zphysics: binding typo fix

- libs/zgui/src/gui.zig
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
This PR enhances `zgui.comboFromEnum` to work with sparse enums such as:
```zig
const SparseEnum = enum(i32) {
first = 10,
second = 100,
third = 1000,
};
```
> fixed comboFromEnum assuming enum int value is consecutive

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
Imgui's internal DockBuilder API has more functions than just these, which are not yet exposed, but these ones I've exposed are sufficient to use the API for basic examples (and for my purposes).
Let me know if there's anything that should be changed. I whipped this up and lightly tested it with my own code, as usual, but if more is needed for this to be merged, I can do more.
> zgui: Expose DockBuilder API - partial coverage implemented and working

- libs/zgui/src/gui.zig
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
Fixed a bug with #541, where the given slice length didn't account for sentinel and would segfault.
Segfault case:
```zig
var buffer: [4:0]u8 = [_:0]u8{ 'w', 'a', 's', 'd' };
zgui.inputText("##", .{.buf = buffer[0..]});
```
`buffer` is actually 5 bytes `'w', 'a', 's', 'd', 0`, but `buffer[0..].len` returns 4. So before this fix, imgui would see the bytes `wasd`, and since it wasn't zero terminated, it would segfault.
> [zgui] fixed off by one for text input due to sentinel

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/src/d3d12.zig
- samples/audio_experiments/src/audio_experiments.zig
- samples/audio_playback_test/src/audio_playback_test.zig
- samples/bindless/src/bindless.zig
- samples/common/src/GuiRenderer.zig
- samples/common/src/common.zig
- samples/directml_convolution_test/src/directml_convolution_test.zig
- samples/mesh_shader_test/src/mesh_shader_test.zig
- samples/minimal_glfw_d3d12/build.zig
- samples/minimal_glfw_d3d12/src/minimal_glfw_d3d12.zig
- samples/rasterization/src/rasterization.zig
- samples/simple_raytracer/src/simple_raytracer.zig
- samples/textured_quad/src/textured_quad.zig
- samples/triangle/src/triangle.zig
Removes all `std.fs.openFileAbsolute` out of `zd3d12.zig`, but there still remain indirect file loading via `gctx.wic_factory.CreateDecoderFromFilename` and `dds_loading.zig`
Can be improved by extracting `csGenerateMipmaps` out of `samples/common/src/hlsl/common.hsls` and put it into zd3d12 with a shader compilation step template.
fixes #556
> BREAKING: changed zd3d12 create*ShaderPipeline and MipmapGenerator to require shader bytecode

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
Since no other derived classes of Shape had yet been exposed, I did this in the way that I thought best fit the pattern laid out in the rest of zphysics.
If this isn't the way we want to go about exposing derived shape classes (in cases like these where the derived class has added functionality that isn't just an overridden virtual method from Shape), then I'd be happy to redo this in whatever way you might prefer.
As usual, I've tested these functions by using them all in my own project, but that's the extent of it.
> zphysics: ConvexHullShape: Some shape-exclusive methods exposed

- libs/zwin32/src/d3d12.zig
- samples/audio_experiments/src/audio_experiments.zig
- samples/audio_playback_test/src/audio_playback_test.zig
- samples/bindless/src/bindless.zig
- samples/common/src/GuiRenderer.zig
- samples/directml_convolution_test/src/directml_convolution_test.zig
- samples/mesh_shader_test/src/mesh_shader_test.zig
- samples/minimal_d3d12/src/minimal_d3d12.zig
- samples/minimal_glfw_d3d12/src/minimal_glfw_d3d12.zig
- samples/rasterization/src/rasterization.zig
- samples/simple_raytracer/src/simple_raytracer.zig
- samples/textured_quad/src/textured_quad.zig
- samples/triangle/src/triangle.zig
According to https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_render_target_blend_desc
`RENDER_TARGET_BLEND_DESC.RenderTargetWriteMask` is the type of `COLOR_WRITE_ENABLE` and defaults to `ALL`.
This explains why there were a bunch of extra `pso_desc.BlendState.RenderTarget[0].RenderTargetWriteMask = 0xf` in our samples, while other d3d12 hello triangles used the default `BLEND_DESC`, which in turn used default `RENDER_TARGET_BLEND_DESC`
> [zd3d12] fixed RenderTargetWriteMask default to be ALL

- libs/zflecs/README.md
- libs/zflecs/src/tests.zig
- libs/zflecs/src/zflecs.zig
This PR adds several comptime functions to `zflecs`, mainly allowing more egornomic system implementatinos, and system addition.
In short, it enables users to do this:
```zig
fn move_system(positions: []Position, velocities: []const Velocity) void {
for (positions, velocities) |*p, v| {
p.x += v.x;
p.y += v.y;
}
}
pub fn main() !void {
...
ecs.ADD_SYSTEM(world, "move system", ecs.OnUpdate, move_system);
...
}
```
Which is more more ergonormic and less error prone than using `*iter_t` and defining queries manually on `system_desc_t`. It also marks the query term as readonly (`.In`) if the array is `const`.
This PR also supports passing `*iter_t` if the user wishes. For instance a user could have something like this:
```zig
fn move_system_with_it(it: *ecs.iter_t, positions: []Position, …
```
> [zflecs]: Implement `comptime` for generating systems and `system_desc_t` from arbitrarly `fn`

- samples/triangle_wgpu/src/triangle_wgpu.zig
The zgpu example init function has a block called `pipline`, so I've changed it to say `pipeline`.
> Fix typo in zgpu example

- libs/zglfw/README.md
The import uses the name `zglfw` but the code in`main()` refers to `glfw`.
> Typo in zglfw example

- libs/zgui/src/gui.zig
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
When `EnumType` is a [non-exhaustive enum](https://ziglang.org/documentation/master/#Non-exhaustive-enum), the follow line attempts to allocate 4 GB at comptime.
```zig
comptime var enum_to_int = std.EnumArray(EnumType, i32).initUndefined();
```
This PR fixes the issue with `StaticStringMap`.
> [zgui] enhanced comboFromEnum to work with non-exhaustive enums

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/src/d3d12.zig
Would close #576
I removed the methods, although to avoid breakage they could be put in as wrappers around the new default constructors at first?
> Removed `init-default` in favor of default struct values

- libs/zd3d12/README.md
- libs/zd3d12/src/zd3d12.zig
- libs/zgpu/README.md
- libs/zgpu/src/zgpu.zig
- libs/zgui/src/gui.zig
- libs/zopenvr/src/system.zig
- libs/zwin32/src/d3d12.zig
- samples/audio_experiments/src/audio_experiments.zig
- samples/audio_experiments_wgpu/src/audio_experiments_wgpu.zig
- samples/audio_playback_test/src/audio_playback_test.zig
- samples/bindless/src/bindless.zig
- samples/bullet_physics_test_wgpu/src/bullet_physics_test_wgpu.zig
- samples/common/src/GuiRenderer.zig
- samples/directml_convolution_test/src/directml_convolution_test.zig
- samples/instanced_pills_wgpu/src/instanced_pills_wgpu.zig
- samples/mesh_shader_test/src/mesh_shader_test.zig
- samples/minimal_d3d12/src/minimal_d3d12.zig
- samples/minimal_glfw_d3d12/src/minimal_glfw_d3d12.zig
- samples/minimal_zgui_glfw_d3d12/src/minimal_zgui_glfw_d3d12.zig
- samples/minimal_zgui_win32_d3d12/src/minimal_zgui_win32_d3d12.zig
- samples/openvr_test/src/openvr_test.zig
- samples/physically_based_rendering_wgpu/src/physically_based_rendering_wgpu.zig
- samples/procedural_mesh_wgpu/src/procedural_mesh_wgpu.zig
- samples/rasterization/src/rasterization.zig
- samples/simple_openvr/src/simple_openvr.zig
- samples/textured_quad/src/textured_quad.zig
- samples/triangle/src/triangle.zig
- samples/triangle_wgpu/src/triangle_wgpu.zig
- samples/vector_graphics_test/src/vector_graphics_test.zig
Added helpers:
1. `fn checkFeatureSupport(gctx: *GraphicsContext, comptime feature: d3d12.FEATURE, data: anytype) HResultError!void`
Purpose: Compile time check to ensure correct data is passed in for feature. 
`HResultError` instead of `HRESULT`.
2. `fn allocRenderTargetView(gctx: *GraphicsContext, handle: ResourceHandle, desc: ?*const d3d12.RENDER_TARGET_VIEW_DESC) d3d12.CPU_DESCRIPTOR_HANDLE`
Purpose: Use `zd3d12.ResourceHandle` instead of `d3d12.IResource`. Allocate required `.RTV` cpu descriptor and returns it.
3. `fn allocDepthStencilView(gctx: *GraphicsContext, handle: ResourceHandle, desc: ?*const d3d12.DEPTH_STENCIL_VIEW_DESC) d3d12.CPU_DESCRIPTOR_HANDLE`
Purpose: Use `zd3d12.ResourceHandle` instead of `d3d12.IResource`. Allocate required `.DSV` cpu descriptor and returns it.
4. …
> [zd3d12] more helper functions

- libs/zgui/src/gui.zig
Fixes ABI issue with zgui DrawList.
There seems to be more use of this ImVector struct that we dont use in zgui which will cause issues elsewhere. I might take a look and fix other ones later ...
> zgui: fix ABI issue for DrawList

- libs/zwin32/build.zig
- samples/audio_experiments/build.zig
- samples/audio_experiments/src/audio_experiments.zig
- samples/audio_playback_test/build.zig
- samples/bindless/build.zig
- samples/directml_convolution_test/build.zig
- samples/mesh_shader_test/build.zig
- samples/minimal_d3d12/build.zig
- samples/minimal_glfw_d3d12/build.zig
- samples/minimal_glfw_d3d12/src/minimal_glfw_d3d12.zig
- samples/rasterization/build.zig
- samples/simple_openvr/build.zig
- samples/textured_quad/build.zig
- samples/triangle/build.zig
Also fixes some instances of https://github.com/zig-gamedev/zig-gamedev/issues/596
When we update to [`zig e342433`](https://github.com/ziglang/zig/commit/e3424332d3fa1264e1f6861b76bb0d1b2996728d#diff-355d0d5a29153bf7f7f73e8e64f0b467b26b2c37e824dcc47e872038a58ce855R1666) we can replace `pathResolve` with `b.pathResolve`
> Extracted dxc command from samples to zwin32 compile shaders step

- libs/zmesh/libs/cgltf/cgltf.h
- libs/zmesh/libs/cgltf/cgltf_write.h
The `CGLTF_API` define already exists in the build script. This change adds `CGLTF_API` to all the extern fns `zcgltf.zig` so that shared library users can link against them.
> cgltf: expose the extern functions referenced in zig code to dll users

- libs/zgui/build.zig
- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
This extra call was causing `artifact("imgui")` calls to fail with an ambiguous artifact error (since "imgui" was being exposed twice).
Also added `setWindowFocus`.
> zgui: remove a redundant installArtifact call, add `setWindowFocus`

- samples/simple_openvr/src/simple_openvr.zig
simple_openvr sample uses a shared root signature.
[d3d12 encourages shared root signatures across pipelines](https://learn.microsoft.com/en-us/windows/win32/direct3d12/root-signatures-overview):
> Ideally, there are groups of Pipeline State Objects (PSOs) that share the same root signature.
[zd3d12 supports shared root signatures](https://github.com/zig-gamedev/zig-gamedev/blob/04b92ef1ca48e07994557edcdae10bd6f86abf9c/libs/zd3d12/src/zd3d12.zig#L1240) on the `GRAPHICS_PIPELINE_STATE_DESC` passed into `createGraphicsShaderPipeline`.
When [`PipelinePool.deinit`](https://github.com/zig-gamedev/zig-gamedev/blob/04b92ef1ca48e07994557edcdae10bd6f86abf9c/libs/zd3d12/src/zd3d12.zig#L2338) it iterates over the pipelines and calls `IRootSignature.Release`.  When …
> simple_openvr: fixed double free on shared root signature

- libs/zsdl/src/sdl3.zig
The latest sturct of KeyboardEvent in SDL3 has been changed.
> Update SDL3 KeyboardEvent struct

- libs/zsdl/README.md
It seems like the build methods from zsdl don't need the `zsdl_path` parameter anymore. Otherwise Zig throws an error.
> Update zsdl example

- libs/zgui/build.zig
- libs/zgui/build.zig.zon
Fixes #628 
Added the includes imgui was looking for when specifically targeting macos.
Also ran into a warning with enums in the system-sdk. It seems to be just a warning that can be silenced with
[this argument](https://github.com/microsoft/vscode-cpptools/issues/10569). Maybe this flag should be macos specific?
> Include macos system sdk and ignore enum warnings

- libs/zbullet/src/zbullet.zig
- libs/zmath/src/util.zig
- libs/zmath/src/zmath.zig
Adding vec-based testing functions that print the failures much better. These use inner expect calls, which will throw an error on the specific mismatch instead of an opaque failure just on the line being false.
> [zmath] Add & use expectVecApproxEqAbs and expectVecEqual.

- libs/zopengl/src/wrapper.zig
Noticed that these were missing from the current wrapper implementation. Let me know if there was a reason for this that I missed!
> zopengl: implement deleteProgram and deleteBuffer functions in wrapper

- libs/zglfw/src/zglfw.zig
- libs/zopengl/src/zopengl.zig
- libs/zsdl/src/sdl2.zig
- libs/zsdl/src/sdl3.zig
Small fix to type as discussed here: https://github.com/zig-gamedev/zig-gamedev/pull/646
> zopengl, zglfw, zsdl: getProcAddress fix name arg type

- libs/zglfw/src/zglfw.zig
- libs/zphysics/README.md
- libs/zphysics/build.zig
- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
- Add support for building `joltc` as a shared library
- Add support for setting `Trace` and `AssertFailed` functions
- Add support for exporting / importing the global state, in order to support dll reloading
- Remove `.kfreebsd` as it's no longer present in std
The DLL reloading use case is somewhat niche, so if that isn't something that makes sense here I'm happy to maintain that part in my own fork.
In my project I use a hot-reload approach where the game dll gets reloaded after code changes, so any global state / vtables need to be updated. For context, I made similar changes here: https://github.com/zig-gamedev/zig-gamedev/pull/230
> zphysics: shared library support

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
Exposes ImGui's ListClipper to have performant lists/tables with lots of items.
I tested it with my own code, and it works as expected.
Let me know if there is anything missing or that should be changed.
> zgui: expose ListClipper API

- libs/zgpu/src/zgpu.zig
allows GraphicsContext.createPipelineLayout to take an empty array of bind group layouts.
> [zgpu] allow for no bind group layouts when creating a pipeline layout

- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
JPH::AABox uses Vec3 which is defined as:
```
union
{
Type     mValue;
float     mF32[4];
};
```
> zphysics: fixup definition of AABox / JPC_AABox

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
Exposes some missing ImGui APIs to monitor performance: `ImGui::GetIO().Framerate`, and `ImGui::ShowMetricsWindow`.
I also added a missing member in the `TableFlags` enum.
Let me know if there is anything missing or that should be changed.
> zgui: Expose Framerate, MetricsWindow and missing TableFlags

- libs/zmesh/build.zig
- libs/zmesh/libs/par_shapes/par_shapes.h
This changes applies PAR_SHAPES_API to all the extern symbols referenced in Shape.zig.
> zmesh: Export par_shapes symbols from the shared library

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
- samples/monolith/src/monolith.zig
DebugRenderer.AABox should have simply been AABox, to reflect Jolt's architecture, and needs to be used for GetLocalBounds.
AABox also should have been using Reals instead of floats, so that is also fixed.
Hopefully this time the ci will like it.
> zphysics: Expose Shape.GetLocalBounds and Shape.CastRay, move AABox to comply with Jolt structure.

- libs/zglfw/src/zglfw.zig
Adds a binding for the `glfwSetErrorCallback` function.
Closes #621.
> zglfw: Add glfw.setErrorCallback

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
Also fixes an error made in the zig version of the SubShapeIDCreator struct.
> zphysics: Expose Shape.GetSurfaceNormal and Shape.GetSupportingFace

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
I was porting another application using Imgui and realized IsMouseDragging() was missing. 
Since the bindings are hand written I'm wondering if there's other discrepancies. I fixed some others I need for now. Also there's overloads which aren't added.
We should consider non hand written in the future for robustness.
I don't know is it's okay to do this, but I changed the return type from MouseClickedCount to u32 since the value doesn't go below 0.
> zgui doesn't cover imgui API, missing drag functionality

- libs/zgpu/src/wgpu.zig
Fixes zig-gamedev/zig-gamedev#697
> [zgpu] Fix definition of CompilationInfoCallback to match libdawn

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/libs/JoltC/JoltPhysicsC_Extensions.cpp
- libs/zphysics/src/zphysics.zig
All tests should now pass with both single and double-precision floats set in Jolt.
> zphysics: Fixed types for double precision support

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
This adds the `ImGui::StyleColors{Dark,Light,Classic}` API to the `zgui.Style` struct.
Compressing these functions to a single function with a style variant argument and naming it `Style.setDefaultColors` is a choice that's up for debate. It seems kinda nice to me, but I'm open to changing it to whatever if people disagree.
> zgui: add ImGui default colors style API

- libs/zgui/build.zig
- libs/zgui/build.zig.zon
- libs/zgui/libs/imgui/misc/freetype/imgui_freetype.cpp
- libs/zgui/libs/imgui/misc/freetype/imgui_freetype.h
- libs/zgui/src/gui.zig
This adds simple build support to have Dear ImGui use the system's FreeType library for nicer-looking fonts.
Bundled FreeType should not be too hard to provide either, but I'd like to see first with the maintainers whether this is something that you'd be interested to include in the project.
> zgui: add support for FreeType font rendering

- build.zig.zon
- experiments/genart/build.zig
- libs/zsdl/README.md
- libs/zsdl/build.zig
- libs/zsdl/build.zig.zon
- samples/minimal_sdl_gl/build.zig
Split `sdl2-prebuilt` into `sdl2-prebuilt-macos`, `sdl2-prebuilt-x86_64-linux-gnu` and `sdl2-prebuilt-x86_64-windows-gnu` and consume them lazily.
> [breaking] refactor zsdl prebuilt libs

- libs/ztracy/build.zig
Closes #693 and #714 
Added option for shared library. Pass `-Dshared=true` to build ztracy as a shared library.
Now passing `-DTRACY_ENABLE` only if the option was specified.
> Add option for shared library. Update -DTRACY_ENABLE option flag

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/libs/JoltC/JoltPhysicsC_Extensions.cpp
- libs/zphysics/src/zphysics.zig
Just one more method and an associated struct.
This is the method used in the Jolt samples, and I've been trying to reproduce the behavior of those samples, so ExtendedUpdate was needed.
In the following days, I'll likely have to expose more too, so I'm not sure whether you'd prefer I lump them all together into a single PR, or do a PR for each thing as I complete it like in this case.
As always, please tell me if I've done anything suboptimally.
The one deleted line was because I noticed a duplicate check, and deleted it. It's unrelated to the additions.
> zphysics: Expose CharacterVirtual.ExtendedUpdate

- libs/zgpu/build.zig
- libs/zgpu/src/zgpu.zig
I hit the default `max_num_bindings_per_group` limit, and was surprised to see the spec calls for a minimum of 640.
Seeing the `BindGroupInfo`/`PipelineLayoutInfo` structs, I understand the limitation, but I think exposing it as build option make sense here.
> [zgpu] Add build options for binding limits

- libs/zglfw/src/zglfw.zig
- libs/zmesh/src/memory.zig
- libs/zphysics/build.zig
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/libs/JoltC/JoltPhysicsC_Extensions.cpp
- libs/zphysics/src/zphysics.zig
- libs/ztracy/build.zig
- libs/ztracy/src/ztracy.zig
A few changes for compiling for `x86_64-windows-msvc`.
- zmesh: use the new `@extern` field, `.is_dll_import`, to link the memory allocation functions from a shared library with the -msvc ABI
- zphysics: fix compilation errors on msvc
- zphysics: fix the definition of JPC_CharacterBaseSettings to account for an MSVC padding quirk
- ztracy: fix compilation under .msvc (define `fileno` -> `_fileno` and fixup export / import defines)
- zglfw: add iconify callback (this is unrelated to msvc but I noticed I had this change locally while upstreaming)
The zmesh change depends on a zig version that includes https://github.com/ziglang/zig/pull/21758 (the change I made to add `.is_dll_import`). This change is included with the latest zig tarballs.
> zmesh, zphysics, and ztracy changes for building for x86_64-windows-msvc

- build.zig.zon
Tested against sdl2_demo for native and emscripten. Both work appropriately.
> Use latest zemscripten
