zig-gamedev/zig-gamedev

- libs/win32/d3d11.zig
added d3d11 bindings relating to:
- input layout creation
- buffer creation
- setting viewports
- clearing render target view
> win32.d3d11 more bindings

- libs/win32/d3d11.zig
added bindings for:
- blend states
- sampler states
- CreateShaderResourceView
- CreateTexture2D
> win32.d3d11 more bindings (3)

- libs/zmath/zmath.zig
- identity
- orthographicLh
- orthographicRh
> zmath: add Matrix functions

- libs/zpool/README.md
This is pretty bare bones, but I hope it is a good start.
> added zpool/README.md

- libs/zpool/README.md
zpool v0.2, credit to Andre Weissflog
> Update pool v0.2 README.md

- libs/common/build.zig
- libs/mach-glfw/build.zig
- libs/zbullet/build.zig
- libs/zd3d12/build.zig
- libs/zgpu/build.zig
- libs/zmath/build.zig
- libs/zmesh/build.zig
- libs/znetwork/build.zig
- libs/znoise/build.zig
- libs/zpix/build.zig
- libs/ztracy/build.zig
- libs/zwin32/build.zig
- libs/zxaudio2/build.zig
Fix breaking change in Zig master, see ziglang/zig#11557
> Change std.build.Pkg.path to std.build.Pkg.source

- libs/zgpu/src/zgpu.zig
- libs/zpool/src/handle.zig
- libs/zpool/src/pool.zig
- samples/bullet_physics_test_wgpu/build.zig
- samples/physically_based_rendering_wgpu/build.zig
- samples/procedural_mesh_wgpu/build.zig
- samples/textured_quad_wgpu/build.zig
- samples/triangle_wgpu/build.zig
- Set `-Dzgpu-dawn-from-source=true` on macOS
- Change obsolete `Pkg.path` to new `Pkg.source` in `zpool/build.zig`
- First naive attempt to add `zgpu` dependency on `zpool`.  This does not work, but I don't understand how it should work.  Please advise.
> Add zgpu dependency on zpool

- libs/zmath/src/benchmark.zig
Thought it'd be interesting to compare. Let me know if you'd like me to recollect the results for this CPU at any point in the future.
> zmath: Add benchmark results from Ryzen 7 5800X

- libs/zwin32/src/winerror.zig
- libs/zwin32/src/xinput.zig
- libs/zwin32/src/zwin32.zig
hardcoded to xinput1_4, which I think pretty much everyone has
> zwin32: add xinput bindings

- libs/zjolt/libs/JoltC/JoltC.cpp
- libs/zjolt/libs/JoltC/JoltC.h
Have I missed anything here?
- closes #92
- closes #93
> JoltC: add JPH_CylinderShapeSettings and JPH_TaperedCapsuleShapeSettings

- libs/zgui/src/zgui.cpp
- libs/zgui/src/zgui.zig
Might be useful when writing custom ui.
> zgui: add DrawList api

- libs/zglfw/src/zglfw.zig
Hi! I just added the set callback functions that I was using prior to the recent change to glfw. I basically just added them as they were previously, but tried to follow what you were doing with the rest of it. Let me know if you'd rather avoid the callbacks, but from what I could tell, its the only way to get some input (for instance, mouse scrolling).
> zglfw: Added fns to set input callbacks.

- libs/zjolt/libs/JoltC/JoltC.cpp
- libs/zjolt/libs/JoltC/JoltC.h
> JoltC: JPH_Body member fns (closes #101)

- libs/zjolt/libs/JoltC/JoltC.cpp
- libs/zjolt/libs/JoltC/JoltC.h
> JoltC: More JPH::Body bindings

- libs/zjolt/libs/JoltC/JoltC.cpp
- libs/zjolt/libs/JoltC/JoltC.h
Declares:
- JPH_AABox
- JPH_Plane
- JPH_Sphere
- JPH_MotionProperties
Defines bindings for
- JPH::MotionProperties
> JoltC: bindings wip

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
> zgui: Add 'addFontFromFileWithConfig'

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
exposed
- ImGui::GetIO().DisplaySize
- ImGui::GetContentRegionMax
- ImGui::GetWindowContentRegionMin
- ImGui::GetWindowContentRegionMax
> zgui exposed more getters

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
1. Rearranged tables api
2. Expose color utility 
3. Update zgui sample to use color utility to get color value
> zgui: expose color utilities

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
I needed these API functions. Not sure at all if I put them in the correct order / place in the source code.
> feat(zgui): add getItemRectMax and getItemRectMin functions

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
Exposes SetClipboardText and GetClipboardText from imgui.
> feat(zgui): add setClipboardText and getClipboardText

- libs/zwin32/src/d3d12.zig
Hello there, I've made some small fixes to make it possible to create `D3D12IHeap`s and `CreatePlacedResource`
Cheers!
> Small fixes to be able to create and use D3D12IHeaps 

- libs/zbullet/src/zbullet.zig
Needed these in my own project so I added them :)
> zbullet: Add missing friction functions.

- libs/zmath/src/zmath.zig
> Skip some failing zmath tests on macOS

- libs/zstbi/src/zstbi.zig
Added `writeToFn` and externs to handle both png and jpg cases similar to `writeToFile`. 
These are useful for cases such as mine where you may want to use a context to write images into a zipped file. 
I do have a question though that could result in adding to this PR:
How do you create a new blank `Image` properly? I'm currently just trying to create the struct as any other struct and allocating bytes for an image width and height, but then I get an error in other code from `Image.deinit()`, as well as the resulting .png seems to be full grey and not transparent as I would have suspected with zeroed data. I suspect it's because there isn't bytes in `data` for the signature and data blocks, that `init` would include. I also tried passing my data to `initFromData`, which works fine when …
> zstbi: Add `writeToFn` and externs

- libs/zd3d12/src/zd3d12.zig
- libs/zgpu/src/zgpu.zig
- libs/zmath/build.zig
- libs/zmath/src/zmath.zig
- libs/zpool/src/embedded_ring_queue.zig
- libs/zpool/src/pool.zig
- libs/zwin32/src/directml.zig
- samples/audio_experiments_wgpu/src/audio_experiments_wgpu.zig
- samples/audio_playback_test/src/audio_playback_test.zig
- samples/bindless/src/bindless.zig
- samples/bullet_physics_test_wgpu/src/bullet_physics_test_wgpu.zig
- samples/gamepad_wgpu/src/gamepad_wgpu.zig
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
- samples/instanced_pills_wgpu/src/vertex_generator.zig
- samples/intro/src/intro2.zig
- samples/intro/src/intro3.zig
- samples/intro/src/intro4.zig
- samples/intro/src/intro6.zig
- samples/mesh_shader_test/src/mesh_shader_test.zig
- samples/minimal/src/minimal.zig
- samples/physically_based_rendering_wgpu/src/physically_based_rendering_wgpu.zig
- samples/physics_test_wgpu/src/physics_test_wgpu.zig
- samples/procedural_mesh_wgpu/src/procedural_mesh_wgpu.zig
- samples/rasterization/src/rasterization.zig
- samples/simple_raytracer/src/simple_raytracer.zig
This updates the new for loop syntax to support latest zig master. 
I also included a small change to the zmath build script to fix running the tests.
> Update to new for loop syntax

- libs/zsdl/src/zsdl.zig
> [zsdl] bindings wip

- libs/zsdl/src/zsdl.zig
Adds `DropEvent` and corresponding variant to `Event` union
> [zsdl] add drop event

- libs/zsdl/src/zsdl.zig
Doesn't actually seem to matter. But better safe than sorry!
> [zsdl] fixup SDL_GetWindowDisplayMode return type

- libs/zstbi/src/zstbi.zig
I am fairly new to zig, but used stbi in the past. I am not very deep into the internas of it.
I tried to puzzle together what has to be done with existing code and the stbi.h
I am not sure if I built zstbi successfully as it is a library. I would appreciate if someone could tell me a way to test if my changes do remotely what I think :)
> zstbi: Added HDR support to Image.loadFromMemory()

- libs/zopengl/src/zopengl.zig
> [zopengl] loadESProfile

- libs/zopengl/src/wrapper.zig
> [zopengl][wrapper] small progress

- libs/zopengl/src/bindings.zig
- libs/zopengl/src/wrapper.zig
- libs/zopengl/src/zopengl.zig
Added `loadExtension` fn and bindings+wrapper for OES_vertex_array_object
> zopengl: extension loading and OES_vertex_array_object

- libs/zopengl/src/wrapper.zig
Adds
- `ParameterName` and `StringName` enums
- ~~`getInteger`~~, `getIntegerv` (I'm not sure about this, see below)
- `getString`
- `getStringi`
> zopengl: more experimental wrappings

- libs/zopengl/src/zopengl.zig
> zopengl: C exports

- libs/zglfw/src/zglfw.zig
Useful for apps that want to delay closing the window or handle unsaved documents etc.
> zglfw: Add `setShouldClose`

- libs/zopengl/src/zopengl.zig
Adds some ES 2.0 bindings that were missed before and some ES 3.0 bindings
> zopengl: ES 2.0 and ES 3.0 bindings additions

- libs/zsdl/src/zsdl.zig
- added getBasePath & getPrefPath 
- added window.getPosition
- fixed up SDL_WindowGetSize
- handle error code consistently
> zsdl: some more coverage

- libs/zgui/src/plot.zig
- libs/zgui/src/zgui.cpp
I noticed I like having the ImPlot demo binding handy to look at all the features quickly. It might be nice to have the official binding in zgui.
Also played around a bit with the Shaded line in ImPlot. Thought you might want it as well.
> Add ImPlot Demo and Shaded Line

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/src/d3d12.zig
- libs/zwin32/src/dds_loader.zig
- samples/bindless/src/bindless.zig
Hello there, I don't have a test for this on zig-gamedev, but we're using this code for Image-Based Lighting for Tides of Revival and it seems to work fine :)
> Add support for loading cubemaps from DDS files

- libs/zflecs/src/zflecs.zig
The changes in this PR are the remaining changes and additions I needed to make to get my project dependent on zflecs to build and run. Please let me know if I need to make any changes or if you want to rework things.
> zflecs: Remaining changes for dependent project

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/build.zig
- libs/zwin32/src/d3d12.zig
- libs/zwin32/src/dxgi.zig
Hello, I'm trying to add support for `ReportLiveObjects()`, but I'm getting a segmentation fault upon invocation and I can't figure out why.
I hope opening a PR might move things along :)
> dxgi: Add support for ReportLiveObjects

- libs/zmath/src/zmath.zig
> zmath: allow for swapping near and far planes for reverse-z

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/libs/JoltC/JoltPhysicsC_Tests.c
- libs/zphysics/src/zphysics.zig
- samples/physics_test_wgpu/src/physics_test_wgpu.zig
I'll likely add more later on, but wanted to get this pushed. 
Added functions:
**JPC_BodyInterface_GetPosition**
**JPC_BodyInterface_GetRotation**
Also added the **JPC_PhysicsUpdateError** return value to **JPC_PhysicsSystem_Update**.
> zphysics: Added a few missing API elements.

- README.md
I'm actually not 100% about "finish build.zig" code blob in readme, but honestly, its super useful when you quickly want to jump in and write something instead fighting with segmentation faults. 😅
> Quick start topic for readme.md

- libs/zsdl/src/zsdl.zig
> fix issue #314

- libs/zphysics/build.zig
- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/libs/JoltC/JoltPhysicsC_Tests.c
- libs/zphysics/src/zphysics.zig
Tests are included, all seems to pass tests.
Comments are included where I thought something needed explaining.
I wanted to write a sample for it to include in samples, and I might do that later still if nobody else does.
> zphysics: DebugRenderer implemented.

- libs/zgui/src/plot.zig
- libs/zgui/src/zgui.cpp
Closes #328
Thanks for the great library!
I'm not really sure about the color parameter?  I also only exposed the `dragPoint` function + flags, not the other "drag tool" things.
> add dragPoint call to zgui.plot

- libs/zgui/src/plot.zig
Sorry about that - that was from your code review but took me a second to hit both spots the rename needed to be.
Related to #328
> rename for consistency

- libs/zjobs/src/zjobs.zig
Related issues: #130, #175
cc @garettbass
> zjobs: Remove use of thread sleep 

- libs/zjobs/src/ring_queue.zig
- libs/zjobs/src/zjobs.zig
Minor code maintenance changes aimed at improving code quality without anything semantically different.
> zjobs: minor code maintenance 

- libs/zsdl/src/sdl2.zig
Just some housekeeping, ordering bindings by API categories per the docs: https://wiki.libsdl.org/SDL2/APIByCategory
This will make it easier to diff SDL2 and SDL3 bindings going forward.
Note that API by Category docs for both SDL2 and SDL3 are missing some items currently. So there will be further changes here to reflect changes to upstream docs.
Upstream SDL wiki PRs:
- https://github.com/libsdl-org/sdlwiki/pull/396
- https://github.com/libsdl-org/sdlwiki/pull/397
> zsdl: Order by API categories per SDL docs

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
Noticed that this one was missing :)
> zgui: Add getMousePos()

- libs/zjobs/src/zjobs.zig
seems like zig commit [3c08fe931a10618950c6af9e89226d1d9b20bbb9](https://github.com/ziglang/zig/commit/3c08fe931a10618950c6af9e89226d1d9b20bbb9) made private decls not visible with @typeInfo. This patch makes all execs functions defined in zjobs test and internally public to avoid any compilation issues caused by the zig commit.
resolve #359
> zjobs: ensure all exec functions are public

- libs/zsdl/src/sdl2.zig
* Fixed `queueAudio` not checking for or returning errors
* Fixed RectF function arg types
* Renamed `RectF` to `FRect` to be consistent with SDL docs and source
* Renamed `PixelFormat` to `PixelFormatEnum` since `PixelFormat` is the name of another SDL type.
* Defined `Bool`, `True` and `False`
* Other small cleanups
> zsdl: bunch of small fixes

- README.md
Hi 👋 
I noticed a couple of spelling mistakes and I thought I would apply a few other quick-fixes that my IDE suggested. 
Since these are some minor changes I hope making a PR directly is okay!
[Here is the rendered version on my fork](https://github.com/aSemy/zig-gamedev/blob/readme-tidy/README.md)
> minor spelling/grammar/formatting fixes in README.md

- libs/zjobs/src/zjobs.zig
Currently zjobs will always be greedy and poll system. With this change the application can choose to submit a custom amount of threads that zjobs should use.
> zjobs: allow setting thread count on queue start

- libs/zflecs/README.md
- libs/zflecs/build.zig
Added
* missing exe.addModule
* missing structs
* expected result
> Fixed zflecs README.md instructions

- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
Let me know if you want me to keep or revert the fmt comments. I added them so that I don't have to revert the formatting changes whenever I save the file (I use format-on-save)
> zphysics: Added BodyInterface.GetMotionType

- libs/zflecs/src/tests.zig
- libs/zflecs/src/zflecs.zig
zflecs: added has_pair and test
> zflecs: fixed set_pair pointer alignment, fixes #381

- libs/zsdl/src/sdl2.zig
- libs/zsdl/src/sdl3.zig
Subject to further change (breaking changes are still being made upstream).
Except for API additions to `Color` that I don't think should be in sdl2.zig, this is complete enough that sdl2.zig and sdl3.zig are diffable.
I will followup with binaries, updated build.zig and make these bindings optionally available to zsdl users in a future PR.
> zsdl: SDL3 bindings WIP

- build.zig
- libs/zsdl/src/zsdl.zig
I think I left this `if (false) {` in by accident
However, it might be best to leave these tests disabled until https://github.com/michal-z/zig-gamedev/issues/312 is resolved
> zsdl: delete temp code & disable zsdl tests in top-level tests

- README.md
- build.zig
- libs/zglfw/README.md
- libs/zglfw/src/zglfw.zig
- samples/minimal_glfw_gl/build.zig
- samples/minimal_glfw_gl/src/minimal_glfw_gl.zig
- samples/minimal_sdl_gl/build.zig
- samples/minimal_sdl_gl/src/minimal_sdl_gl.zig
* zglfw: added `windowHint`, `windowHintString` and `windowHintTyped`
* zglfw: deprecated `WindowHint.set` (see comment)
* zglfw: defined `ContextRobustness`, `ReleaseBehaviour` and `ContextCreationApi`
* zglfw: added `getProcAddress`
* added minimal_glfw_gl sample
* renamed minimal_gl to minimal_sdl_gl
> minimal glfw opengl sample

- README.md
i had to search around for this since the flags keep changing, and wasn't sure what the defaults were in the 500 lines of code of the build file. i would expect this repo and samples to be most game developer's first try with zig, so i think having the optimization options at least mentioned could prevent some people from having a skewed first impression of perf capability in a real world game/app. anyway, hope its helpful
> update readme for optimization flags

- libs/zbullet/src/zbullet.zig
Implemented/Onboarded the cbtBodyApplyTorque function from CBullet, matching formatting as understood.
> Update to onboard applyBodyTorque()

- README.md
- build.zig
- libs/zopengl/build.zig
- libs/zopengl/src/wrapper.zig
- libs/zopengl/src/zopengl.zig
* Adds a simple compile test
* Fix some compile errors in wrapper (Zig 0.12.0-dev.464)
> Add zopengl tests and wrapper fixes

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/src/wincodec.zig
Hello 👋 
We've started working on UI for Tides of Revival and we encountered this missing format from wincoded.
> Add support for 2-bit depth textures

- libs/zmesh/libs/cgltf/cgltf.c
- libs/zmesh/libs/cgltf/cgltf.h
- libs/zmesh/libs/cgltf/cgltf_write.h
- libs/zmesh/src/zcgltf.zig
Several new api aren't exposed yet. Maybe we can wait until they're actually needed?
> zmesh: update to latest cgltf, add cgltf_write

- libs/zd3d12/src/zd3d12.zig
Hello Michal, we've accidentally pushed some commented out code in one of our previous PRs.
Sorry for the issue 😅
> Restore accidentally commented out code

- README.md
- libs/zopengl/build.zig.zon
- libs/zopengl/src/wrapper.zig
Increases wrapper coverage to 100% of OpenGL 1.0 core profile
> zopengl: wrapper progress

- libs/zaudio/src/zaudio.zig
Fixes custom DataSources which can now be implemented by embedding a `DataSourceBase` in a custom struct:
```zig
const CustomDataSource = struct {
base: DataSourceBase,
other_fields: u1,
};
```
Apologies that this is split into 2 PRs...
> custom DataSource fixes

- build.zig
- libs/zsdl/build.zig
- libs/zsdl/src/sdl2.zig
- libs/zsdl/src/sdl3.zig
- libs/zsdl/src/zsdl.zig
Only supports macOS with libSDL3.dylib installed in /usr/local/lib for now
> zsdl: preliminary sdl3 option

- libs/zmath/src/util.zig
Not sure if there's a better way to do this, I first wrote it using `select` but not sure it would be better so changed to this simpler version.
> zmath: Added setTranslationVec

- libs/zgui/src/gui.zig
Missed the padding edit from my vendored copy, apologies!
> Missed fixing leftover padding field for #496

- libs/zglfw/src/zglfw.zig
- samples/frame_pacing_wgpu/screenshot.png
- samples/frame_pacing_wgpu/src/frame_pacing_wgpu.zig
> [zglfw] exposed glfwGetMonitorName and glfwGetVideoModes

- libs/zflecs/src/tests.zig
- libs/zflecs/src/zflecs.zig
These are in flecs addons flecs.h and ecs_new_w_pair is used in the manual for how to get started with flecs.
https://github.com/SanderMertens/flecs/blob/31c3db4f963cb35e44784eea411695514006f24c/include/flecs/addons/flecs_c.h#L298
> Add ecs_new_w_pair and ecs_delete_children

- libs/zjobs/src/ring_queue.zig
- libs/zjobs/src/zjobs.zig
- libs/zmesh/src/zcgltf.zig
- libs/zopengl/src/zopengl.zig
Please see here https://github.com/ziglang/zig/blob/cd62005f19ff966d2c42de4daeb9a1e4b644bf76/lib/std/builtin.zig#L338
This was causing zmesh and other lib tests to fail.
> Rename builtin enums to lower case for 0.12.0-dev.3428+d8bb139da

- libs/zflecs/src/zflecs.zig
- libs/zstbi/src/zstbi.zig
From this change ziglang here
This fixes the zstbi and zflecs tests in latest master
https://github.com/ziglang/zig/commit/cd62005f19ff966d2c42de4daeb9a1e4b644bf76
> Update os -> posix change in 0.12.0-dev.3428+d8bb139da

- libs/zgui/libs/imgui/backends/imgui_impl_glfw.cpp
I miss this little hack during update to new version.
> [zgui][fix] bad mouse position with zgui+glfw and hidpi on macOS

- libs/zgui/src/gui.zig
- libs/zgui/src/zgui.cpp
Add binding for ImGui's GetItemRectSize function.
> Add binding for GetItemRectSize

- build.zig
- libs/zgui/build.zig
- libs/zgui/libs/imgui/backends/imgui_impl_glfw.cpp
- libs/zgui/libs/imgui/backends/imgui_impl_win32.cpp
- libs/zgui/src/backend_dx12.zig
- libs/zgui/src/backend_win32_dx12.zig
- libs/zgui/src/gui.zig
- samples/minimal_zgui_win32_d3d12/build.zig
- samples/minimal_zgui_win32_d3d12/minimal_zgui_win32_d3d12_content/Roboto-Medium.ttf
- samples/minimal_zgui_win32_d3d12/src/minimal_zgui_win32_d3d12.zig
> zgui win32 dx12

- libs/zd3d12/src/zd3d12.zig
- libs/zwin32/src/d3d12.zig
- samples/minimal_glfw_d3d12/src/minimal_glfw_d3d12.hlsl
- samples/minimal_glfw_d3d12/src/minimal_glfw_d3d12.zig
as compared to without the helper: https://github.com/zig-gamedev/zig-gamedev/blob/e3b637d83fb906f1b6faf7195f568652ccc76ad0/samples/common/src/GuiRenderer.zig#L133-L236
> [zd3d12] added helpers to upload vertices and vertex indices

- samples/bindless/build.zig
- samples/rasterization/build.zig
- samples/simple_openvr/build.zig
- samples/textured_quad/build.zig
Didn't detect this bug when testing #599 since I had existing cached files.
> fixed csGenerateMipmaps output filename

- samples/frame_pacing_wgpu/src/frame_pacing_wgpu.zig
- samples/openvr_test/src/openvr_test.zig
- samples/physics_test_wgpu/src/physics_test_wgpu.zig
- samples/simple_openvr/src/simple_openvr.zig
added frame rate limiter to physics_test_wgpu as physics was frame rate based
> [samples] refactored to use std.time constants

- libs/zgpu/README.md
Hello! I noticed that zgpu's README was missing a couple quotes. Thanks!
> Fix zgpu README Typos

- libs/zgui/src/plot.zig
- libs/zgui/src/zgui.cpp
A couple more implot functions I've tested within my demos.
> More implot functions

- libs/zflecs/build.zig
This is a change i did for my usage and thought i should make a PR in case people needed it.
> add build as shared option option

- libs/zopengl/src/wrapper.zig
> zopengl: implement generateMipmap in wrapper

- libs/zsdl/README.md
Unsure what the correct usage is here. This updates the zsdl README to match the minimal_sdl_gl sample.
> Unclear zsdl usage instructions

- libs/zgui/README.md
- libs/zgui/build.zig
- libs/zgui/build.zig.zon
- libs/zgui/libs/node_editor/LICENSE
- libs/zgui/libs/node_editor/crude_json.cpp
- libs/zgui/libs/node_editor/crude_json.h
- libs/zgui/libs/node_editor/imgui_bezier_math.h
- libs/zgui/libs/node_editor/imgui_bezier_math.inl
- libs/zgui/libs/node_editor/imgui_canvas.cpp
- libs/zgui/libs/node_editor/imgui_canvas.h
- libs/zgui/libs/node_editor/imgui_extra_math.h
- libs/zgui/libs/node_editor/imgui_extra_math.inl
- libs/zgui/libs/node_editor/imgui_node_editor.cpp
- libs/zgui/libs/node_editor/imgui_node_editor.h
- libs/zgui/libs/node_editor/imgui_node_editor_api.cpp
- libs/zgui/libs/node_editor/imgui_node_editor_internal.h
- libs/zgui/libs/node_editor/imgui_node_editor_internal.inl
- libs/zgui/src/gui.zig
- libs/zgui/src/node_editor.zig
- libs/zgui/src/zgui.cpp
- samples/gui_test_wgpu/src/gui_test_wgpu.zig
Add support for [ImGui-node-editor](https://github.com/thedmd/imgui-node-editor)
> [zgui] Add Node Editor support

- libs/zflecs/build.zig
- libs/zflecs/libs/flecs/flecs.c
- libs/zflecs/libs/flecs/flecs.h
- libs/zflecs/src/zflecs.zig
All 11 tests run successfully, haven't done any additional testing.
> zflecs: Update to flecs 4.0.1

- build.zig
- libs/zd3d12/src/zd3d12.zig
- libs/zphysics/libs/JoltC/JoltPhysicsC.cpp
- libs/zphysics/libs/JoltC/JoltPhysicsC.h
- libs/zphysics/src/zphysics.zig
- libs/zpix/README.md
- libs/zwin32/src/d3d12.zig
- samples/zphysics_instanced_cubes_d3d12/README.md
- samples/zphysics_instanced_cubes_d3d12/build.zig
- samples/zphysics_instanced_cubes_d3d12/screenshot.png
- samples/zphysics_instanced_cubes_d3d12/src/zphysics_instanced_cubes_d3d12.hlsl
- samples/zphysics_instanced_cubes_d3d12/src/zphysics_instanced_cubes_d3d12.zig
- samples/zphysics_instanced_cubes_d3d12/zphysics_instanced_cubes_d3d12_content/Roboto-Medium.ttf
Original PR from @Pyrolistical: https://github.com/zig-gamedev/zig-gamedev/pull/679
> Pyro cubes

- libs/zglfw/src/zglfw.zig
- libs/zgui/src/gizmo.zig
- libs/zgui/src/gui.zig
- libs/zgui/src/node_editor.zig
- libs/zgui/src/plot.zig
- libs/zgui/src/zgui.cpp
- libs/zmath/src/zmath.zig
- libs/zmesh/src/zcgltf.zig
- libs/zpool/src/pool.zig
- libs/zpool/src/utils.zig
- `zgui,` `zglfw,` `zmath,` `zmesh,` `zpool:` update for 0.14.0-dev changes
- `zgui:` add `endFrame`
See:  https://github.com/ziglang/zig/pull/21225
I didn't see a 0.14.0 branch here, but feel free to retarget this to another branch as this might not make sense to merge to main yet.
> Update zgui, zglfw, zmath, zmesh, and zpool for the latest 0.14.0-dev breaking changes

- README.md
- libs/zgpu/src/zgpu.zig
Fixes zig-gamedev/zig-gamedev#698
> [zgpu] Remove kfreebsd as it is no longer supported by zig

- libs/zsdl/src/sdl2.zig
- libs/zsdl/src/sdl3.zig
- Adds [GetTicks](https://wiki.libsdl.org/SDL2/SDL_GetTicks) to zsdl2
- Adds [GetTicks](https://wiki.libsdl.org/SDL3/SDL_GetTicks) to zsdl3
> [zsdl] Add GetTicks

- libs/zsdl/src/sdl2.zig
Created export for SDL_UpdateTexture. 
I hereby waive all rights to the source code contained in this pull request in favor of the Zig-Gamedev community.
> [zsdl] Added SDL_UpdateTexture call

- libs/ztracy/README.md
Updating ztracy readme. Hopefully makes it easier to get other projects up and running with ztracy!
If the `const options` is too much I can rework it.
> update ztracy readme instruction

- libs/zsdl/src/sdl2.zig
Added a few zsdl functions for texture and surface handling, making it easier to use the sdl backend a bit.
I hereby waive all rights to the source code contained in this pull request in favor of the Zig-Gamedev community.
> [zsdl] Added texture and surface handling functions

- build.zig.zon
- samples/minimal_zgui_glfw_d3d12/src/minimal_zgui_glfw_d3d12.zig
- samples/minimal_zgui_win32_d3d12/src/minimal_zgui_win32_d3d12.zig
- samples/openvr_test/src/openvr_test.zig
- samples/zphysics_instanced_cubes_d3d12/src/zphysics_instanced_cubes_d3d12.zig
zgui D3d12 backend breaking change introduced by upgrade to Dear Imgui 1.91.8. See https://github.com/zig-gamedev/zgui/pull/15
> zgui update to dear imgui 1.91.8
